---
title: CUW Art Gallery
timezone: UTC
collections:
  header:
    title: Headers
    output: false
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: headers
  values:
    headers:
    - home
    - about
    - student-work
author: Jordan Kelly
email: jordan.kelly@arbor.edu
description: The CUW Art Gallery was founded with the hope of educating, challenging,
  and inspiring the students, faculty, staff, and community of CUW as well as the
  public through exposure to the vast world of art.
show_excerpts: false
plugins:
- jekyll-feed
- jekyll-seo-tag
