---
title: CUW Art Gallery
timezone: America/Chicago
collections:
  banners:
    title: Banners
    output: false
  exhibits:
    title: Exhibits
    output: true
    layout: exhibit
  posts:
    title: Student Gallery
    output: true
  uploads:
    title: Uploads
    output: true
author: Jordan Kelly
email: jordan.kelly@arbor.edu
description: The CUW Art Gallery was founded with the hope of educating, challenging,
  and inspiring the students, faculty, staff, and community of CUW as well as the
  public through exposure to the vast world of art.
plugins:
- jekyll-feed
- jekyll-seo-tag
main-nav_pages:
- index.markdown
- about.markdown
- student-work.markdown
social:
  facebook: https://www.facebook.com/CUWArtGallery/
  twitter: 
  linkedin: 
